### PR TITLE
Tighten up text around usage of the jakarta namespace. 

### LINKED ISSUE #7: Tighten up the text regarding usage of the jakarta.* namespace
The Jakarta EE Specification Committee has decided to add a clarification that using the `jakarta` namespace is not allowed for any deployment, including applications used by TCKs.

### PR DESCRIPTION
**Pull request by ivargrimstad**
A first attempt on the text regarding the namespace clarification. 

NOTE that this PR will have to be approved by the spec committee before merging!
The approval will be done in a 7-day ballot as defined by the JESP itself.

Will close #7.

### CODE REVIEW

**Comment by starksm64** [comment]
+1

**Comment by tjwatson** [comment]
+1

**Comment by scottmarlow** [comment]
:+1: from `TCK Scott` as well!

**Comment by kazumura** [comment]
Are there any documents that define the word "API artifacts" ?

**Comment by starksm64** [comment]
perhaps add a qualification in parenthesis after API artifacts saying (all API jars, javadoc, and schema namespaces)

**Comment by kazumura** [comment]
+1

**Comment by dblevins** [comment]
There was a specific question if just applications were limited or if tests themselves were also limited. The text does read as specifically deployments and applications are limited, which maybe doesn't answer that question unambiguously. Perhaps we could tighten this up and address any future scenarios. 

Maybe something along the lines of " must not be used by applications, TCKs, tools, libraries or other assets produced by Specification Projects."

Thoughts?

**Comment by ivargrimstad** [comment]
Approved by the Specification Committee:

<div style="box-sizing: border-box;">

Representative | Representative for: | Vote
-- | -- | --
Kenji Kazumura | Fujitsu | +1
Tom Watson, Emily Jiang | IBM | +1
Ed Bratt, Dmitry Kornilov | Oracle | +1
Andrew Pielage, Petr Aubrecht | Payara | +1
David Blevins, Jean-Louis Monteiro | Tomitribe | +1
Ivar Grimstad | EE4J PMC | +1
Marcelo Ancelmo, Martijn Verburg | Participant Members | +1
Werner Keil | Committer Members | +1
Jun Qian | Enterprise Members | +1
Zhai Luchao | Enterprise Members | +1
  | Total | 10

Non-binding votes | Vote
-- |  --
Jan Westerkamp  | -1

</div><div style="box-sizing: border-box;"><br style="box-sizing: border-box; color: rgb(76, 77, 78); font-family: Roboto, &quot;Libre Franklin&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(249, 249, 249); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

https://www.eclipse.org/lists/jakarta.ee-spec/msg02258.html

**Comment by dblevins** [comment]
Note, we need to update the version to 1.3

**Comment by ivargrimstad** [comment]
This change has been approved by the Jakarta EE Specification Committee, Steering Committee, and the Executive Director according to process.

@waynebeaton Please merge this PR and label a 1.3 release

**Comment by waynebeaton** [comment]
I've granted the specification committee write access. I don't think that you need me as a gatekeeper.

**Pull request merged**
